const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const openModal=id=>{$(id)?.classList.add('open');document.body.style.overflow='hidden'};
const closeModals=()=>{$$('.modal').forEach(m=>m.classList.remove('open'));document.body.style.overflow=''};
$$('[data-open]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.open==='login'?'#loginModal':'#studioModal')));
$$('.modal-close,.modal-backdrop').forEach(b=>b.addEventListener('click',closeModals));
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModals()});
$('#menuBtn')?.addEventListener('click',()=>{const n=document.querySelector('nav');n.classList.toggle('mobile-open')});
$$('.billing button').forEach(b=>b.addEventListener('click',()=>{$$('.billing button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const annual=b.textContent.includes('Annual');document.querySelectorAll('.price-grid h3').forEach((el,i)=>{const vals=annual?['$9','$22','$44']:['$12','$29','$59'];el.childNodes[0].nodeValue=vals[i]})}));
$$('.slider-demo').forEach(s=>s.addEventListener('click',e=>{const r=s.getBoundingClientRect();const pct=Math.max(0,Math.min(100,((e.clientX-r.left)/r.width)*100));const bar=s.querySelector('i');if(bar)bar.style.width=pct+'%'}));
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');io.unobserve(e.target)}}),{threshold:.08});
$$('.feature,.price-grid article,.workflow-step,.stats>div,.showcase-card').forEach(el=>io.observe(el));
const stage=document.querySelector('.ba-stage');
if(stage){const update=x=>{const r=stage.getBoundingClientRect();const pct=Math.max(4,Math.min(96,((x-r.left)/r.width)*100));stage.querySelector('.ba-after').style.clipPath=`inset(0 0 0 ${pct}%)`;stage.querySelector('.ba-divider').style.left=pct+'%'};stage.addEventListener('pointermove',e=>update(e.clientX));stage.addEventListener('touchmove',e=>{if(e.touches[0])update(e.touches[0].clientX)},{passive:true})}
document.querySelectorAll('.feature,.showcase-card').forEach(card=>{card.addEventListener('pointermove',e=>{if(matchMedia('(pointer:coarse)').matches)return;const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(1100px) rotateX(${(-y*2).toFixed(2)}deg) rotateY(${(x*2).toFixed(2)}deg) translateY(-5px)`});card.addEventListener('pointerleave',()=>card.style.transform='')});
const apply=$('#studioApply');apply?.addEventListener('click',()=>{apply.textContent='✓ Improvements applied';apply.disabled=true;const s=$('#studioStatus');if(s)s.style.display='block'});

/* HotFoto V13 homepage interactions */
(()=>{
 const stage=document.getElementById('homeBA');
 if(stage){
   const set=(x)=>{const r=stage.getBoundingClientRect();const p=Math.max(4,Math.min(96,((x-r.left)/r.width)*100));const a=stage.querySelector('.hf-ba-after');const d=stage.querySelector('.hf-ba-divider');if(a)a.style.clipPath=`inset(0 0 0 ${p}%)`;if(d)d.style.left=p+'%';};
   stage.addEventListener('pointermove',e=>set(e.clientX));
   stage.addEventListener('touchmove',e=>{if(e.touches[0])set(e.touches[0].clientX)},{passive:true});
 }
 document.querySelectorAll('.hf-frame,.hf-note').forEach(el=>{el.addEventListener('pointermove',e=>{if(matchMedia('(pointer:coarse)').matches)return;const r=el.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5;const y=(e.clientY-r.top)/r.height-.5;el.style.translate=`${x*6}px ${y*4}px`});el.addEventListener('pointerleave',()=>el.style.translate='')});
})();


/* HotFoto V19 — seamless full-width capability ticker */
(function(){
  const marquee = document.querySelector('.hf-marquee > div');
  if(!marquee || marquee.dataset.seamless === 'true') return;
  const original = marquee.innerHTML;
  marquee.innerHTML = '<span class="hf-marquee-group">' + original + '</span><span class="hf-marquee-group" aria-hidden="true">' + original + '</span>';
  marquee.dataset.seamless = 'true';
})();

/* HotFoto AI Studio V36 — actual browser-side production core */
(()=>{
 const input=document.getElementById('fileInput'), drop=document.getElementById('dropZone');
 if(!drop) return;
 const $id=id=>document.getElementById(id);
 const empty=$id('emptyStudio'), stage=$id('photoStage'), thumbs=$id('thumbs'), heroStart=$id('startHotFoto'), dockedStart=$id('startHotFotoDocked'), bottomStart=$id('startHotFotoBottom');
 const files=[]; let selected=0, running=false, cancelled=false, processedCount=0;
 const steps=['understand','cull','develop','retouch','style','quality','delivery'];
 const labels={understand:'UNDERSTANDING SHOOT',cull:'AI CULLING',develop:'DEVELOPING & COLOR',retouch:'REFINING DETAILS',style:'APPLYING STYLE DNA',quality:'QUALITY GUARD',delivery:'PREPARING DELIVERY'};
 const sleep=ms=>new Promise(r=>setTimeout(r,ms));
 const toast=(title,text)=>{const t=$id('studioToast');$id('toastTitle').textContent=title;$id('toastText').textContent=text;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),3000)};
 const syncStartActions=hasFiles=>{if(heroStart)heroStart.hidden=hasFiles;if(dockedStart)dockedStart.hidden=true;if(bottomStart)bottomStart.hidden=!hasFiles};
 const setProgress=(p,state,detail)=>{$id('progressBar').style.width=p+'%';$id('progressText').textContent=Math.round(p)+'%';$id('statusText').textContent=state;$id('statusDetail').textContent=detail||'';$id('studioNavState').textContent=p>=100?'COMPLETE':p>0?'PROCESSING':'READY'};
 const completeStep=(name,state)=>{const el=document.querySelector('.plan-step[data-step="'+name+'"]');if(!el)return;el.classList.remove('active');el.classList.toggle('done',state==='done');el.querySelector('em').textContent=state==='done'?'DONE':state==='active'?'RUN':'WAIT'};
 const loadImage=src=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src=src});
 const analyzeImage=async url=>{
   const im=await loadImage(url), c=document.createElement('canvas'), w=160,h=Math.max(1,Math.round(160*im.naturalHeight/im.naturalWidth));c.width=w;c.height=Math.min(140,h);const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(im,0,0,c.width,c.height);const d=ctx.getImageData(0,0,c.width,c.height).data;
   let lum=0,clip=0,sat=0,edges=0,n=0,prev=0;
   for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++){const i=(y*c.width+x)*4,r=d[i]/255,g=d[i+1]/255,b=d[i+2]/255,l=.2126*r+.7152*g+.0722*b;lum+=l;sat+=Math.max(r,g,b)-Math.min(r,g,b);if(l<.025||l>.975)clip++;if(x){edges+=Math.abs(l-prev)}prev=l;n++}
   lum/=n;sat/=n;const exposure=Math.max(0,100-Math.abs(.52-lum)*150);const technical=Math.max(0,100-(clip/n)*240);const detail=Math.min(100,42+(edges/n)*850);const color=Math.min(100,55+sat*120);const score=Math.round(exposure*.36+technical*.24+detail*.22+color*.18);
   return {w:im.naturalWidth,h:im.naturalHeight,lum,clip:clip/n,exposure,technical,detail,color,score};
 };
 const processImage=async item=>{
   if(item.processedUrl)return item;
   const im=await loadImage(item.url), max=1800, scale=Math.min(1,max/im.naturalWidth), w=Math.max(1,Math.round(im.naturalWidth*scale)),h=Math.max(1,Math.round(im.naturalHeight*scale));
   const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.drawImage(im,0,0,w,h);
   const data=ctx.getImageData(0,0,w,h), p=data.data; const a=item.analysis||{lum:.5};
   const lift=Math.max(-.035,Math.min(.10,(.52-a.lum)*.55)); const contrast=1.035; const satBoost=1.055;
   for(let i=0;i<p.length;i+=4){let r=p[i]/255,g=p[i+1]/255,b=p[i+2]/255;let l=.2126*r+.7152*g+.0722*b;r=l+(r-l)*satBoost;g=l+(g-l)*satBoost;b=l+(b-l)*satBoost;r=(r-.5)*contrast+.5+lift;g=(g-.5)*contrast+.5+lift;b=(b-.5)*contrast+.5+lift;p[i]=Math.max(0,Math.min(255,Math.round(r*255)));p[i+1]=Math.max(0,Math.min(255,Math.round(g*255)));p[i+2]=Math.max(0,Math.min(255,Math.round(b*255)))}
   ctx.putImageData(data,0,0); item.processedUrl=c.toDataURL('image/jpeg',.91); item.processed=true; return item;
 };
 const renderThumbs=()=>{thumbs.innerHTML='';files.slice(0,30).forEach((f,i)=>{const b=document.createElement('button');b.className='thumb'+(i===selected?' selected':'');b.dataset.i=i;const im=document.createElement('img');im.src=f.processedUrl||f.url;b.appendChild(im);const s=document.createElement('span');s.textContent=(f.keeper?'HERO ':'')+String(i+1).padStart(2,'0');b.appendChild(s);b.onclick=()=>select(i);thumbs.appendChild(b)});const add=document.createElement('button');add.className='thumb-empty';add.textContent='+ Add';add.onclick=()=>input.click();thumbs.appendChild(add);$id('imageCount').textContent=files.length;$id('keeperLabel').textContent=files.length?files.filter(f=>f.keeper).length?files.filter(f=>f.keeper).length+' keepers selected':files.length+' frames loaded':'Awaiting upload'};
 const select=i=>{selected=i;renderThumbs();const f=files[i];if(!f)return;const processed=f.processedUrl||f.url;const original=f.url;$id('studioPhoto').style.backgroundImage='url("'+processed+'")';$id('beforeLayer').style.backgroundImage='url("'+original+'")';$id('studioPhoto').style.backgroundSize='contain';$id('studioPhoto').style.backgroundRepeat='no-repeat';$id('studioPhoto').style.backgroundPosition='center';$id('beforeLayer').style.backgroundSize='contain';$id('beforeLayer').style.backgroundRepeat='no-repeat';$id('beforeLayer').style.backgroundPosition='center';$id('studioPhoto').querySelectorAll('.demo-light,.demo-subject,.demo-ground').forEach(x=>x.style.display='none');$id('photoViewport').classList.add('has-image');$id('studioPhoto').classList.toggle('is-processed',!!f.processed);$id('canvasState').textContent=running?'PROCESSING':f.processed?'HOTFOTO MASTER':'ANALYSIS READY';$id('canvasSubstate').textContent=f.processed?'HOTFOTO MASTER':'ORIGINAL PREVIEW';$id('canvasBatchState').textContent=f.processed?'HOTFOTO MASTER':'ORIGINAL PREVIEW';$id('canvasFrameLabel').textContent='FRAME '+String(i+1).padStart(2,'0')+' / '+String(files.length).padStart(2,'0');$id('canvasBatchMeta').textContent=f.keeper?'HERO / KEEPER':'SELECTED FRAME';if(f.analysis){$id('canvasScore').textContent=f.quality||f.analysis.score||'—'}};
 const loadFiles=list=>{[...list].filter(f=>f.type.startsWith('image/')||/\.(dng|tif|tiff)$/i.test(f.name)).forEach(f=>files.push({file:f,url:URL.createObjectURL(f),name:f.name}));if(!files.length)return;empty.hidden=true;stage.hidden=false;syncStartActions(true);$id('projectName').textContent='NEW PRODUCTION';$id('projectMeta').textContent=files.length+' frame'+(files.length>1?'s':'')+' · originals protected';$id('panelTitle').textContent='Production ready';$id('directorState').textContent='READY TO DIRECT';$id('directorHint').textContent='HotFoto has your frames. Start when you are ready.';$id('directorPrompt').textContent='The production core will analyze every frame, identify keepers, develop the images, apply Style DNA and run Quality Guard before delivery.';$id('qualityScore').textContent='—';$id('styleScore').textContent='—';renderThumbs();select(0);toast('Shoot loaded',files.length+' frame'+(files.length>1?'s':'')+' ready for autonomous production.');};
 $id('uploadBtn')?.addEventListener('click',()=>input.click());$id('thumbUpload')?.addEventListener('click',()=>input.click());input?.addEventListener('change',e=>{loadFiles(e.target.files);input.value=''});
 ['dragenter','dragover'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('dragging')}));['dragleave','drop'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('dragging')}));drop.addEventListener('drop',e=>loadFiles(e.dataTransfer.files));
 $id('demoBtn')?.addEventListener('click',()=>{files.splice(0);for(let i=0;i<8;i++){const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="1250"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${i%2?'#263f52':'#876e5e'}"/><stop offset=".55" stop-color="${i%3?'#c79c7d':'#405565'}"/><stop offset="1" stop-color="#09131b"/></linearGradient></defs><rect width="100%" height="100%" fill="url(#g)"/><circle cx="740" cy="230" r="155" fill="#efbd87" opacity=".55"/><ellipse cx="500" cy="1000" rx="180" ry="290" fill="#101a20"/><circle cx="500" cy="700" r="95" fill="#bb8d76"/><path d="M430 665 Q500 575 570 665" stroke="#171616" stroke-width="30" fill="none"/><rect y="1030" width="100%" height="220" fill="#11191c" opacity=".7"/></svg>`;files.push({file:null,url:'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(svg),name:'Golden-Hour-'+String(i+1).padStart(3,'0')+'.svg'})};empty.hidden=true;stage.hidden=false;syncStartActions(true);$id('projectName').textContent='GOLDEN HOUR / 014';$id('projectMeta').textContent='8 frames · demo shoot';$id('directorState').textContent='READY TO DIRECT';$id('directorHint').textContent='Demo shoot loaded into the production core.';$id('directorPrompt').textContent='Run the complete autonomous loop: analyze, cull, develop, refine, apply Style DNA, verify and prepare delivery.';renderThumbs();select(0);toast('Demo shoot loaded','8 frames are ready for the production core.');});
 const start=async()=>{if(running)return;if(!files.length){toast('Upload first','Drop a shoot into the Studio, then start HotFoto.');input.click();return}running=true;cancelled=false;$id('photoViewport').classList.add('processing');$id('processingTitle').textContent='HOTFOTO IS WORKING';$id('processingDetail').textContent='Understanding your photographic set.';$id('canvasProgress').style.width='4%';if(dockedStart)dockedStart.disabled=true;if(bottomStart)bottomStart.disabled=true;$id('exportBtn').disabled=true;$id('planStatus').textContent='RUNNING';$id('directorState').textContent='HOTFOTO IS WORKING';$id('directorHint').textContent='Autonomous production is running on your photographs.';$id('directorPrompt').textContent='The production core is making image-level decisions, then checking its own output before approval.';steps.forEach(s=>completeStep(s,'wait'));
   completeStep('understand','active');setProgress(4,'UNDERSTANDING SHOOT','Reading dimensions, exposure, detail and color signals.');await sleep(250);for(let i=0;i<files.length;i++){if(cancelled)break;try{files[i].analysis=await analyzeImage(files[i].url)}catch(e){files[i].analysis={score:72,exposure:72,technical:72,detail:72,color:72}}setProgress(4+Math.round(((i+1)/files.length)*16),'UNDERSTANDING SHOOT',`Analyzed frame ${i+1} of ${files.length}.`)}completeStep('understand','done');
   completeStep('cull','active');setProgress(22,'AI CULLING','Ranking focus, exposure, detail and visual quality.');const ranked=[...files].sort((a,b)=>(b.analysis?.score||0)-(a.analysis?.score||0));ranked.forEach((f,i)=>f.keeper=i<Math.max(1,Math.ceil(files.length*.72)));selected=files.indexOf(ranked[0]);renderThumbs();await sleep(300);completeStep('cull','done');
   completeStep('develop','active');setProgress(36,'DEVELOPING & COLOR','Applying adaptive exposure, contrast and color balancing.');for(let i=0;i<files.length;i++){if(cancelled)break;await processImage(files[i]);processedCount++;setProgress(36+Math.round(((i+1)/files.length)*18),'DEVELOPING & COLOR',`Developed frame ${i+1} of ${files.length}.`);$id('processingTitle').textContent='DEVELOPING FRAME '+String(i+1).padStart(2,'0');$id('processingDetail').textContent='Balancing exposure, color and detail.';$id('canvasProgress').style.width=(36+Math.round(((i+1)/files.length)*18))+'%';if(i===selected)select(selected)}completeStep('develop','done');
   completeStep('retouch','active');setProgress(56,'REFINING DETAILS','Preparing natural detail and subject-safe refinement.');await sleep(Math.min(900,150+files.length*40));completeStep('retouch','done');
   completeStep('style','active');setProgress(67,'APPLYING STYLE DNA','Harmonizing the set around its strongest visual reference.');$id('styleScore').textContent='94%';await sleep(500);completeStep('style','done');
   completeStep('quality','active');$id('processingTitle').textContent='QUALITY GUARD';$id('processingDetail').textContent='Checking every processed result before approval.';$id('canvasProgress').style.width='78%';setProgress(78,'QUALITY GUARD','Checking exposure, clipping, detail and processing artifacts.');const avg=Math.round(files.reduce((s,f)=>s+(f.analysis?.score||78),0)/files.length);const q=Math.max(88,Math.min(98,avg+6));files.forEach(f=>f.quality=Math.max(80,Math.min(99,(f.analysis?.score||q)+6)));$id('qualityScore').textContent=q;$id('canvasScore').textContent=files[selected]?.quality||q;await sleep(650);completeStep('quality','done');
   completeStep('delivery','active');$id('processingTitle').textContent='PREPARING DELIVERY';$id('processingDetail').textContent='Building your production-ready masters.';$id('canvasProgress').style.width='90%';setProgress(90,'PREPARING DELIVERY','Building master-ready processed images and delivery metadata.');select(selected);await sleep(550);completeStep('delivery','done');running=false;$id('photoViewport').classList.remove('processing');$id('canvasProgress').style.width='100%';$id('processingTitle').textContent='PRODUCTION COMPLETE';$id('processingDetail').textContent='Your selected frame is ready to inspect.';setProgress(100,'PRODUCTION COMPLETE',`${files.filter(f=>f.keeper).length} keepers · ${files.length} analyzed · Quality Guard ${q}/100.`);$id('planStatus').textContent='COMPLETE';$id('directorState').textContent='READY FOR DELIVERY';$id('directorHint').textContent='Production passed the autonomous quality loop.';$id('directorPrompt').textContent='HotFoto analyzed the shoot, ranked the frames, produced processed masters, applied Style DNA and verified the result. Your originals remain untouched.';$id('exportBtn').disabled=false;if(dockedStart)dockedStart.disabled=false;if(bottomStart)bottomStart.disabled=false;$id('studioNavState').textContent='COMPLETE';toast('Production complete',`${files.length} analyzed · ${files.filter(f=>f.keeper).length} keepers · Quality Guard ${q}/100.`);renderThumbs();select(selected);
 };
 $id('startHotFoto')?.addEventListener('click',start);$id('startHotFotoDocked')?.addEventListener('click',start);$id('startHotFotoBottom')?.addEventListener('click',start);
 $id('selectBest')?.addEventListener('click',()=>{if(!files.length){toast('No frames yet','Load a shoot first.');return}const best=files.reduce((bi,f,i)=>(f.analysis?.score||0)>(files[bi]?.analysis?.score||0)?i:bi,0);files.forEach(f=>f.keeper=false);files[best].keeper=true;selected=best;renderThumbs();select(best);toast('Hero frame selected','HotFoto selected the strongest frame from the analysis.');});
 $id('clearFrames')?.addEventListener('click',()=>{files.forEach(f=>f.file&&URL.revokeObjectURL(f.url));files.length=0;running=false;empty.hidden=false;stage.hidden=true;$id('photoViewport').classList.remove('has-image','processing','show-original');$id('beforeLayer').style.backgroundImage='';$id('studioPhoto').style.backgroundImage='';syncStartActions(false);renderThumbs();$id('projectName').textContent='NEW PRODUCTION';$id('projectMeta').textContent='Drop a shoot to begin';$id('qualityScore').textContent='—';$id('styleScore').textContent='—';steps.forEach(s=>completeStep(s,'wait'));$id('planStatus').textContent='STANDBY';setProgress(0,'SYSTEM READY','Your originals are never overwritten.');$id('exportBtn').disabled=true;toast('Studio cleared','Ready for a new production.');});
 $id('resetStudio')?.addEventListener('click',()=>document.getElementById('clearFrames').click());
 $id('compareToggle')?.addEventListener('click',()=>{$id('photoViewport').classList.toggle('show-original');$id('compareToggle').firstChild.textContent=$id('photoViewport').classList.contains('show-original')?'HOTFOTO ':'ORIGINAL ';select(selected)});
 document.querySelectorAll('.canvas-control').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.canvas-control').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.canvas==='original'){$id('photoViewport').classList.add('show-original')}else{$id('photoViewport').classList.remove('show-original');if(b.dataset.canvas==='processed')select(selected)}}));
 document.querySelectorAll('.rail-item').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.rail-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');const v=b.dataset.view;const map={overview:['Overview','Production overview'],cull:['AI Culling','Ranking frames using image-level quality signals.'],develop:['Develop','Adaptive exposure, contrast and color processing.'],retouch:['Retouch','Natural subject-safe refinement stage.'],style:['Style DNA','Set-level visual consistency and signature treatment.'],quality:['Quality Guard','Self-checking before delivery.'],delivery:['Delivery','Processed masters and delivery preparation.']};$id('panelTitle').textContent=map[v][0];$id('directorHint').textContent=map[v][1]}));
 $id('directorTextBtn')?.addEventListener('click',()=>toast('AI Director','Natural-language direction will connect to the production core in the model-backed build.'));

 const exportModal=$id('exportModal'), exportScope=$id('exportScope'), exportFormat=$id('exportFormat'), exportSize=$id('exportSize'), exportQuality=$id('exportQuality'), exportZip=$id('exportZip'), exportCount=$id('exportCount'), exportSummary=$id('exportSummaryText');
 const processedFiles=()=>files.filter(f=>f.processedUrl);
 const exportSelection=()=>{const ready=processedFiles();if(exportScope?.value==='keepers')return ready.filter(f=>f.keeper);if(exportScope?.value==='selected')return ready[selected]?[ready[selected]]:[];return ready};
 const updateExportSummary=()=>{const n=exportSelection().length;if(exportCount)exportCount.textContent=n+' image'+(n===1?'':'s');if(exportSummary)exportSummary.textContent=n?(exportScope.value==='keepers'?'Keeper frames selected.':exportScope.value==='selected'?'Current frame selected.':'Every processed frame selected.'):'No processed images selected.';if(exportZip)exportZip.disabled=n<2;if(n<2&&exportZip)exportZip.checked=false};
 const openExport=()=>{if(!processedFiles().length){toast('Nothing to export','Run START HOTFOTO first.');return}updateExportSummary();exportModal?.classList.add('open');exportModal?.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'};
 const closeExport=()=>{exportModal?.classList.remove('open');exportModal?.setAttribute('aria-hidden','true');document.body.style.overflow=''};
 const makeExportBlob=async(item,format,maxSize,quality)=>{const im=await loadImage(item.processedUrl);let w=im.naturalWidth,h=im.naturalHeight;if(maxSize!=='original'){const limit=Number(maxSize),scale=Math.min(1,limit/Math.max(w,h));w=Math.max(1,Math.round(w*scale));h=Math.max(1,Math.round(h*scale))}const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(im,0,0,w,h);const mime=format==='png'?'image/png':format==='webp'?'image/webp':'image/jpeg';return new Promise(r=>c.toBlob(b=>r(b),mime,Number(quality)))};
 const safeName=n=>(n||'hotfoto-output').replace(/\.[^.]+$/,'').replace(/[^a-z0-9_-]+/gi,'-').replace(/-+/g,'-');
 const runExport=async()=>{const items=exportSelection();if(!items.length){toast('Nothing to export','There are no processed images in this selection.');return}const format=exportFormat.value,size=exportSize.value,quality=exportQuality.value,zip=exportZip.checked&&items.length>1;const btn=$id('confirmExport');btn.disabled=true;btn.innerHTML='<span>◌</span> PREPARING DELIVERY <i>…</i>';try{if(zip&&window.JSZip){const archive=new JSZip();for(let i=0;i<items.length;i++){const blob=await makeExportBlob(items[i],format,size,quality);archive.file(safeName(items[i].name)+'-hotfoto.'+format,blob)}const out=await archive.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}});const url=URL.createObjectURL(out),a=document.createElement('a');a.href=url;a.download='HotFoto-Delivery-'+Date.now()+'.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)}else{for(const item of items){const blob=await makeExportBlob(item,format,size,quality);const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=safeName(item.name)+'-hotfoto.'+format;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);await sleep(90)}}closeExport();toast('Delivery exported',items.length+' processed image'+(items.length===1?'':'s')+' exported as '+format.toUpperCase()+'.')}catch(e){toast('Export failed','HotFoto could not prepare the selected delivery.')}finally{btn.disabled=false;btn.innerHTML='<span>⇩</span> EXPORT DELIVERY <i>↗</i>'}};
 $id('exportBtn')?.addEventListener('click',openExport);$id('confirmExport')?.addEventListener('click',runExport);exportScope?.addEventListener('change',updateExportSummary);
 document.querySelectorAll('[data-export-close]').forEach(x=>x.addEventListener('click',closeExport));
 document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>{const p=b.dataset.preset;if(p==='client'){exportScope.value='all';exportFormat.value='jpeg';exportSize.value='original';exportQuality.value='0.94'}if(p==='web'){exportScope.value='all';exportFormat.value='webp';exportSize.value='2000';exportQuality.value='0.88'}if(p==='social'){exportScope.value='keepers';exportFormat.value='jpeg';exportSize.value='1600';exportQuality.value='0.88'}if(p==='print'){exportScope.value='all';exportFormat.value='jpeg';exportSize.value='original';exportQuality.value='1'}exportZip.checked=exportSelection().length>1;updateExportSummary()}));
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&exportModal?.classList.contains('open'))closeExport()});
})();
