(() => {
 const $=id=>document.getElementById(id); const endpoint=$('endpoint'),token=$('token'),projectId=$('projectId');
 endpoint.value=localStorage.getItem('hotfotoGatewayEndpoint')||'';
 const authToken=localStorage.getItem('hotfotoSessionToken')||''; if(authToken) token.value=authToken;
 const api=async(path,options={})=>{const base=(endpoint.value||'').trim().replace(/\/$/,''); if(!base) throw Error('Gateway endpoint required'); const headers={'Content-Type':'application/json',...(token.value?{Authorization:'Bearer '+token.value}:{}),...(options.headers||{})}; const r=await fetch(base+path,{...options,headers}); const data=await r.json().catch(()=>({})); if(!r.ok||data.ok===false) throw Error(data.error||`HTTP ${r.status}`); return data};

 const reviewProof=async(id,card)=>{const box=card.querySelector('.proof-review');if(!box.hidden){box.hidden=true;return}box.hidden=false;box.innerHTML='Loading proof…';try{const r=await api('/delivery/proof',{method:'POST',body:JSON.stringify({deliveryId:id})});const p=r.proof||{}, actions=p.actions||[];const selected=actions.filter(a=>a.action==='select'&&a.value===true);const fav=actions.filter(a=>a.action==='favorite'&&a.value===true);const comments=actions.filter(a=>a.action==='comment'&&a.comment);box.innerHTML=`<div class="proof-summary"><b>${selected.length} selected</b><span>${fav.length} favorites</span><span>${comments.length} comments</span>${p.clientName?`<span>from ${escapeHtml(p.clientName)}</span>`:''}</div>${comments.length?comments.map(c=>`<div class="proof-comment"><strong>${escapeHtml(c.assetId||'Frame')}</strong><p>${escapeHtml(c.comment)}</p></div>`).join(''):'<p class="muted">No written comments.</p>'}${selected.length?`<p class="muted">Selected asset IDs: ${selected.map(x=>escapeHtml(x.assetId)).join(', ')}</p>`:''}` }catch(e){box.innerHTML=`<p class="muted">${escapeHtml(e.message)}</p>`}};
 const setStatus=(x,good=false)=>{$('status').textContent=x;$('status').style.color=good?'#9fe0b7':''};
 const render=items=>{const h=$('history');if(!items.length){h.innerHTML='<div class="history-empty"><span>✦</span><h3>No deliveries yet</h3><p>Publish the selected frames when the production is ready.</p></div>';return}h.innerHTML=items.map(d=>{const base=(endpoint.value||'').replace(/\/$/,''); const link=base+'/share/'+encodeURIComponent(d.token||''); const share=d.shareUrl||link; return `<article class="history-item" data-delivery="${escapeHtml(d.id)}"><div class="row"><div><h3>${escapeHtml(d.title)}</h3><small>${escapeHtml(d.status||'published')} · ${d.assetIds?.length||0} assets · ${d.expiresAt?new Date(d.expiresAt).toLocaleDateString():'no expiry'} · proof ${escapeHtml(d.proofStatus||'open')}</small></div><b>${d.proofStatus==='submitted'?'READY TO REVIEW':''}</b></div>${d.token?`<code>${escapeHtml(share)}</code>`:''}<div class="history-tools"><button class="ghost-btn review-proof" data-id="${escapeHtml(d.id)}">Review proof</button>${d.token?`<button class="ghost-btn copy-link" data-link="${escapeHtml(share)}">Copy link</button>`:''}</div><div class="proof-review" hidden></div></article>`}).join('');document.querySelectorAll('.review-proof').forEach(b=>b.onclick=()=>reviewProof(b.dataset.id,b.closest('.history-item')));document.querySelectorAll('.copy-link').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(b.dataset.link);b.textContent='Copied';setTimeout(()=>b.textContent='Copy link',1200)}catch{prompt('Copy this link',b.dataset.link)}})};
 const escapeHtml=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
 $('publish').onclick=async()=>{try{$('publish').disabled=true;setStatus('Publishing…');const ids=$('assetIds').value.split(',').map(x=>x.trim()).filter(Boolean);const days=Number($('expiry').value);const expiresAt=days?new Date(Date.now()+days*86400000).toISOString():null;localStorage.setItem('hotfotoGatewayEndpoint',endpoint.value.trim());localStorage.setItem('hotfotoSessionToken',token.value.trim());const d=await api('/delivery/create',{method:'POST',body:JSON.stringify({projectId:projectId.value.trim(),title:$('title').value.trim(),assetIds:ids,expiresAt,options:{proofing:true,downloads:true}})});const base=endpoint.value.replace(/\/$/,''); const publicLink=location.origin+location.pathname.replace('delivery.html','share.html')+'?gateway='+encodeURIComponent(base)+'&token='+encodeURIComponent(d.delivery.token); setStatus('Published. Private link created.',true);render([{...d.delivery,token:d.delivery.token,shareUrl:publicLink},...(await api('/delivery/list',{method:'POST',body:JSON.stringify({projectId:projectId.value.trim()})})).deliveries]);}catch(e){setStatus(e.message||'Publish failed')}finally{$('publish').disabled=false}};
 $('refresh').onclick=async()=>{try{const r=await api('/delivery/list',{method:'POST',body:JSON.stringify({projectId:projectId.value.trim()})});render(r.deliveries)}catch(e){setStatus(e.message)}};
 $('projectId').value=new URLSearchParams(location.search).get('project')||'';
})();
