(()=>{
 const q=new URLSearchParams(location.search),gateway=(q.get('gateway')||localStorage.getItem('hotfotoGatewayEndpoint')||location.origin).replace(/\/$/,''),token=q.get('token');
 const state=document.getElementById('state'),gallery=document.getElementById('gallery'),grid=document.getElementById('grid');
 const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
 const clientKey=(()=>{const k='hotfotoProofClient_'+(token||'');let v=localStorage.getItem(k);if(!v){v='client_'+crypto.randomUUID().replaceAll('-','');localStorage.setItem(k,v)}return v})();
 let delivery=null,assets=[],proof={actions:[]},activeCommentAsset=null;
 const fail=m=>{state.innerHTML=`<div class="pulse">×</div><h1>Delivery unavailable.</h1><p>${esc(m)}</p>`};
 const actionFor=(assetId,action)=>proof.actions.find(a=>String(a.assetId)===String(assetId)&&a.action===action&&a.clientKey===clientKey);
 const counts=()=>{const selected=assets.filter(a=>actionFor(a.id,'select')?.value===true).length;const fav=assets.filter(a=>actionFor(a.id,'favorite')?.value===true).length;document.getElementById('selectionCount').textContent=`${selected} selected`;document.getElementById('favoriteCount').textContent=` · ${fav} favorite${fav===1?'':'s'}`};
 const render=()=>{counts();grid.innerHTML=assets.map(a=>{const sel=actionFor(a.id,'select')?.value===true,fav=actionFor(a.id,'favorite')?.value===true,c=actionFor(a.id,'comment')?.comment||'';const url=a.download?.url;return `<article class="gallery-item ${sel?'selected':''}" data-id="${esc(a.id)}">${url?`<img loading="lazy" src="${esc(url)}" alt="${esc(a.name)}">`:`<div class="fallback">✦</div>`}<div class="label"><span class="name">${esc(a.name)}</span><span class="frame-tools"><button class="frame-tool ${sel?'active':''}" data-action="select" title="Select">✓</button><button class="frame-tool ${fav?'active':''}" data-action="favorite" title="Favorite">♥</button><button class="frame-tool comment" data-action="comment" title="Comment">✎</button></span></div>${c?`<div class="comment-chip">Comment saved</div>`:''}</article>`}).join('');};
 const api=async(path,body)=>{const r=await fetch(gateway+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw Error(d.error||`HTTP ${r.status}`);return d};
 async function load(){if(!token){fail('This private delivery link is incomplete.');return}try{const r=await fetch(`${gateway}/share/${encodeURIComponent(token)}`);const d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||'The delivery could not be opened.');if(d.delivery.status==='expired')throw Error('This private delivery has expired.');delivery=d.delivery;assets=d.assets||[];proof=d.proof||{actions:[]};document.getElementById('title').textContent=delivery.title||'Your photographs';document.getElementById('meta').textContent=`${assets.length} selected photograph${assets.length===1?'':'s'} · ${delivery.proofStatus==='submitted'?'Proof submitted':'Select, favorite or comment on frames'}`;if(delivery.proofStatus==='submitted'){document.getElementById('submitted').hidden=false;document.getElementById('submitted').textContent=`Proof submitted${delivery.clientName?' by '+delivery.clientName:''} · Your photographer has your selections.`;document.getElementById('submitProof').disabled=true}render();state.hidden=true;gallery.hidden=false}catch(e){fail(e.message||'The delivery could not be opened.')}}
 grid.addEventListener('click',async e=>{const btn=e.target.closest('.frame-tool');if(!btn)return;const card=btn.closest('.gallery-item'),assetId=card?.dataset.id,action=btn.dataset.action;if(!assetId)return;if(action==='comment'){activeCommentAsset=assetId;document.getElementById('commentTitle').textContent=`Comment on ${assets.find(a=>a.id===assetId)?.name||'frame'}`;document.getElementById('commentText').value=actionFor(assetId,'comment')?.comment||'';document.getElementById('commentModal').hidden=false;return}const current=actionFor(assetId,action)?.value===true;try{const r=await api('/share/proof/action',{token,assetId,clientKey,action,value:!current});const old=proof.actions.findIndex(a=>a.assetId===r.action.assetId&&a.action===r.action.action&&a.clientKey===clientKey);if(old>=0)proof.actions[old]=r.action;else proof.actions.push(r.action);render()}catch(err){alert(err.message)}});
 const close=()=>{document.getElementById('commentModal').hidden=true;activeCommentAsset=null};document.getElementById('closeComment').onclick=close;document.getElementById('cancelComment').onclick=close;
 document.getElementById('saveComment').onclick=async()=>{if(!activeCommentAsset)return;try{const comment=document.getElementById('commentText').value.trim();const r=await api('/share/proof/action',{token,assetId:activeCommentAsset,clientKey,action:'comment',comment,value:true});const i=proof.actions.findIndex(a=>a.assetId===activeCommentAsset&&a.action==='comment'&&a.clientKey===clientKey);if(i>=0)proof.actions[i]=r.action;else proof.actions.push(r.action);close();render()}catch(err){alert(err.message)}};
 document.getElementById('refreshProof').onclick=load;
 const submitModal=document.getElementById('submitModal');document.getElementById('submitProof').onclick=()=>{if(!assets.some(a=>actionFor(a.id,'select')?.value===true)){if(!confirm('No photographs are selected. Submit anyway?'))return}submitModal.hidden=false};
 const closeSubmit=()=>submitModal.hidden=true;document.getElementById('closeSubmit').onclick=closeSubmit;document.getElementById('cancelSubmit').onclick=closeSubmit;
 document.getElementById('confirmSubmit').onclick=async()=>{try{const name=document.getElementById('clientName').value.trim();const email=document.getElementById('clientEmail').value.trim();if(!name)throw Error('Please enter your name.');const r=await api('/share/proof/submit',{token,clientKey,clientName:name,clientEmail:email});delivery.proofStatus='submitted';delivery.clientName=name;delivery.submittedAt=r.submittedAt;closeSubmit();document.getElementById('submitted').hidden=false;document.getElementById('submitted').textContent=`Proof submitted by ${name}. Your photographer has your selections.`;document.getElementById('submitProof').disabled=true;document.getElementById('meta').textContent=`${assets.length} selected photograph${assets.length===1?'':'s'} · Proof submitted`; }catch(err){alert(err.message)}};
 load();
})();
